### ISSUE TITLE
[1.12.2] JEHC not showing presser/trap recipes anymore.

### ISSUE THREAD

**Issue by Geethebluesky** [pearxteam/just-enough-harvestcraft#5]
I'm not sure when this started happening, but with the latest JEI (jei_1.12.2-4.9.1.175 as of 2018/05/02) and JEHC build 1.5.0, the recipes simply don't show anymore.

Here's the [full latest.log](https://gist.github.com/Geethebluesky/99619405c7ea792df213754f6566658b). Relevant bit shows this:

> [16:39:00] [main/INFO]: Starting JEI...
> [16:39:00] [main/INFO]: Registering recipe categories...
> [16:39:00] [main/ERROR]: Failed to register mod categories: class ru.pearx.jehc.jei.JEHCPlugin
> java.lang.IllegalArgumentException: A RecipeCategory with UID "jehc.presser" has already been registered.
> 	at mezz.jei.startup.ModRegistry.addRecipeCategories(ModRegistry.java:92) ~[ModRegistry.class:?]
> 	at ru.pearx.jehc.jei.JEHCPlugin.registerCategories(JEHCPlugin.java:50) ~[JEHCPlugin.class:?]
> 	at mezz.jei.startup.JeiStarter.registerCategories(JeiStarter.java:156) ~[JeiStarter.class:?]
> 	at mezz.jei.startup.JeiStarter.start(JeiStarter.java:59) ~[JeiStarter.class:?]
> 	at mezz.jei.startup.ProxyCommonClient.lambda$loadComplete$0(ProxyCommonClient.java:116) ~[ProxyCommonClient.class:?]
> 	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110544_b(SimpleReloadableResourceManager.java:131) [cev.class:?]
> 	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110541_a(SimpleReloadableResourceManager.java:112) [cev.class:?]
> 	at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:806) [bib.class:?]
> 	at com.mumfrey.liteloader.client.ResourcesClient.refreshResources(ResourcesClient.java:45) [ResourcesClient.class:1.12.2-SNAPSHOT+jnks-b4.git-4cc2bb00c8eff08863c9f7625be08983951546a5]
> 	at com.mumfrey.liteloader.client.LiteLoaderEventBrokerClient.onStartupComplete(LiteLoaderEventBrokerClient.java:275) [LiteLoaderEventBrokerClient.class:1.12.2-SNAPSHOT+jnks-b4.git-4cc2bb00c8eff08863c9f7625be08983951546a5]
> 	at net.minecraft.client.Minecraft.handler$onStartupComplete$zzj000(Minecraft.java:3390) [bib.class:?]
> 	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:569) [bib.class:?]
> 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377) [bib.class:?]
> 	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_172]
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_172]
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_172]
> 	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_172]
> 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
> 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]

Mod list+versions:

MC 1.12.2 with forge-1.12.2-14.23.3.**2678**-universal.jar
Baubles-1.12-1.5.2.jar
BetterFps-1.4.8.jar
foamfix-0.9.9-1.12.2-anarchy.jar
JEHC-1.12.2-1.5.0.0.jar
jei_1.12.2-4.9.1.175.jar
mod_voxelMap_1.7.0_for_1.12.2.litemod
OptiFine_1.12.2_HD_U_D2.jar
Pam's+HarvestCraft+1.12.2t.jar
Liteloader 1.12.2-00-SNAPSHOT (latest version available)

**Comment by mrapplexz** [comment]
Hello. Sorry for not responding so much time. I'm busy at the moment. Currently, can you try to detect which mod conflicts with JEHC? When I'm free, I will fix this issue.

**Comment by Geethebluesky** [comment]
I'll do a mod-by-mod on the above since I do have some time. I figured one of them might have jumped out at you from there so I didn't do it sooner. Will edit :)

**Comment by Geethebluesky** [comment]
Finally, I could see the Presser tab after loading through Forge alone (without LiteLoader).
This also eliminates the error I quoted above.

Whenever I set my MC profile to use LL again though, the tab disappears and the error comes back.

No other mods (LL or not) have to be loaded for this to happen.

That should be enough to replicate the issue, otherwise let me know :)

**Comment by mrapplexz** [comment]
Okay, thanks for the info! I'll try to reproduce and fix this issue today.

**Comment by mrapplexz** [comment]
Fixed in 1.5.1.
