### ISSUE TITLE
add Water Filter

### ISSUE THREAD

**Issue by TimGoll** [pearxteam/just-enough-harvestcraft#8]
Add missing "machines" like the water filter. It was only today that I learned you can produce 8 salt by filtering water. It should be shown inside of JEI

**Comment by mrapplexz** [comment]
The Water Filter support has been already added in 1.6.0 (17535f9d2785d4a4f3edf266b87cef2f9763bdfa).

**Comment by TimGoll** [comment]
Cool. Then there must be a conflict with another mod. Thanks anyway

**Comment by mrapplexz** [comment]
What version of JEHC do you use?

**Comment by TimGoll** [comment]
The newest on curse for 1.12.2

**Comment by mrapplexz** [comment]
Just rechecked with JEHC 1.6.1, Pam's HarvestCraft 1.12.2y, JEI 4.12.0.215. Works for me ¯\\\_(ツ)_/¯.
![image](https://user-images.githubusercontent.com/7630912/44620881-98266480-a8b5-11e8-9099-b730e9bbb862.png)

**Comment by TimGoll** [comment]
I have a suspicion. I think the error is caused by UniDict (I'll check it later). Because I don't have Pam's salt. I can only use the salt of PrimalCore. Therefore the Filter recipe moght be unusable.

**Comment by TimGoll** [comment]
I shifted the priority of harvestcraft in unidict to the top. Now the recipe is shown.
