### ISSUE TITLE
Harvestcraft update

### ISSUE THREAD

**Issue by TimGoll** [pearxteam/just-enough-harvestcraft#9]
Harvestcraft added a new recipe you have to add:
`Added: Recipe: Hazelnut to flour`

**Comment by mrapplexz** [comment]
It seems that the recipe actually hasn't been added.
I haven't found anything related to it in https://github.com/MatrexsVigil/harvestcraft/commit/003a600c8310535369b5bced60a191568e7f970c.

**Comment by TimGoll** [comment]
Strange, because she has added it to the changelog. But she also said she added oredict to all new crops which she forgot to do
